env: DEV
pcd_server_name: VM-DWHSQLDEV04   
pcd_database: Process_Control_Data
pcd_user: ssis_user
pcd_password: ssis_user
job_agent_server_name: VM-DWHSQLDEV04
job_name: 999_Source_DataLoad_to_MID_Dev
log_location: C:\Users\AlvinEstrada\Codes\logs
#
# Below are use to fetch the data base on the date range
# dd, Day
# mm, Month
# hh, Hour
# mi, Minute
# ss, Second
interval: mm    

# (-) indicate a reverse value
interval_number: -3  

# CURRENT_TIMESTAMP (DEFAULT) to use todays datetime, similar to SYSDateTime, or GetDate
# 2020-12-16 20:06:00:00
# Please Note: if you are using CURRENT_TIMESTAMP please ensure that your where clause have this format
#              Default syntax for iterative run
#                 > WHERE <key_column> betweeN DATEADD({0}, {1}, '{2}') AND '{3}'
#              Else if you want to use CURRENT_TIMESTAMP
#                 > WHERE <key_column> betweeN DATEADD({0}, {1}, CURRENT_TIMESTAMP) AND CURRENT_TIMESTAMP
date_time: 2021-08-30 18:00:00
# 2021-04-30 18:00:00
# 


# CURRENT_TIMESTAMP


